export default {
steemit: 'Steemit',
    busy: 'STEEMTag',
esteem: 'eSteem',
chainbb: 'chainBB',
utopian: 'Utopian',
dtube: 'DTube',
dlive: 'DLive',
dmania: 'dMania',
dsound: 'DSound',
steepshot: 'Steepshot',
zappl: 'Zappl',
steemkr: 'Steemkr',
timer: 'Timer',
steemjs: 'Steem.js',
strimi: 'Strimi',
classifieds: 'Classifieds',
steemtag: 'STEEMTag',
upfundme: 'UPFund.me',
steemhumor: 'SteemHumor',
steemgroups: 'STEEMGroups',
steemtag: 'STEEMTag',
steempipe: 'STEEMPipe',
};
